- hosts: all
  remote_user: root
  roles:
    - common

- hosts: gitlab_runners
  remote_user: root
  roles:
    - docker
    - gitlab_runner

- hosts: docker
  remote_user: root
  roles:
    - docker

- hosts: r
  remote_user: root
  roles:
    - emacs
    - docker
    - r-base
    - r

- hosts: scala
  remote_user: root
  roles:
    - emacs
    - docker
    - r-base
    - scala
    